title: John Doe
description: > # this means to ignore newlines until "baseurl:"
  I am John Doe & I really like to take pictures. Below you'll find some of my work & links to find me elsewhere on the internet.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

#Information that is used to create the Terms of Service & Privacy Policy pages
company: Company Name
location: Location
start-year: 2016

# Usernames for Socail Media accoutns
twitter_username: example
instagram_username: example
facebook_username: example

# Build settings
markdown: kramdown
exclude: [node_modules, package.json, gulpfile.js, README.md]
include: [_pages]
